# Generated by Django 3.1.3 on 2020-11-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
