# Generated by Django 3.1.2 on 2020-12-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
