# Generated by Django 3.1.2 on 2020-12-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
