# Generated by Django 3.1.2 on 2020-12-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editari', '0002_student_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_online',
        ),
    ]
