# Generated by Django 3.1.2 on 2020-11-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editari', '0002_auto_20201117_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isOnline',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
